### ISSUE TITLE
Could share some turorials  about J519?

### ISSUE THREAD

**Issue by chuangwang1991** [gavanderhoorn/packet-fanuc-stream-motion-j519#1]
I'm glad to see the project about J519, could you share some turorials? 

During my work, I generate the tracjectory points(every 8 ms) , but I don't know how to send to robot and make the robot move to test the tracjectory, and I have little infos about J519.

 waiting for your response, thanks a lot.

**Comment by gavanderhoorn** [comment]
Unfortunately, no, I don't have anything to share at this time.

The documentation Fanuc provides is pretty decent for J519, so you should be able to get things to work, provided you have some experience with network protocols.

**Comment by gavanderhoorn** [comment]
I'm going to close this, as it's not really an issue with the Wireshark dissector we host here.

Feel free to keep commenting on the issue, even after I've closed it.
